# Generated by Django 3.0.5 on 2020-04-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200407_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ploeg',
            fields=[
                ('ploeg_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=20)),
                ('korte_naam', models.CharField(max_length=5)),
                ('leeftijdscategorie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seizoen',
            fields=[
                ('seizoen_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=20)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField()),
                ('bezig', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lid',
            name='functies',
        ),
        migrations.CreateModel(
            name='PloegLid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Functie')),
                ('lid_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Lid')),
                ('ploeg_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Ploeg')),
            ],
        ),
        migrations.AddField(
            model_name='ploeg',
            name='seizoen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Seizoen'),
        ),
    ]
