# Generated by Django 3.0.5 on 2020-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200411_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='sportief_lid',
            field=models.BooleanField(default=False),
        ),
    ]
