# Generated by Django 3.0.5 on 2020-04-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_lid_sportief_lid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lid",
            old_name="moeder_id",
            new_name="moeder",
        ),
        migrations.RenameField(
            model_name="lid",
            old_name="vader_id",
            new_name="vader",
        ),
    ]
