# Generated by Django 3.0.5 on 2020-05-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_auto_20200503_1618"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lid",
            old_name="straatnaam",
            new_name="straatnaam_en_huisnummer",
        ),
        migrations.RemoveField(
            model_name="lid",
            name="bus",
        ),
        migrations.RemoveField(
            model_name="lid",
            name="huisnummer",
        ),
    ]
