# Generated by Django 3.0.5 on 2020-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_auto_20200517_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betaling",
            name="mails_verstuurd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
