# Generated by Django 4.1.2 on 2022-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0019_lid_actief_lid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lid",
            name="familieleden",
            field=models.ManyToManyField(blank=True, to="management.lid"),
        ),
    ]
