# Generated by Django 3.0.5 on 2020-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='extra_informatie',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
