name: Run tests for betalingen

on: [pull_request]

jobs:
  test-betalingen:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
        django-version: ["4"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: |
            3.10
      - name: Install poetry 1.2.2
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run python manage.py test management --parallel --settings=donza.settings.test
